USE CasinoManagementSystemDB;
GO

DELETE FROM Aktywacja_Promocji;
DELETE FROM Sesja_gry;
DELETE FROM Zakup;
DELETE FROM Wizyta;
DELETE FROM Pracownik;
DELETE FROM Promocja;
DELETE FROM Gra;
DELETE FROM Gracz;
DELETE FROM Kasyno;

-- Reset liczników
BEGIN TRY DBCC CHECKIDENT ('Aktywacja_Promocji', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Sesja_gry', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Zakup', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Wizyta', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Pracownik', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Promocja', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Gra', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Gracz', RESEED, 0); END TRY BEGIN CATCH END CATCH;
BEGIN TRY DBCC CHECKIDENT ('Kasyno', RESEED, 0); END TRY BEGIN CATCH END CATCH;
GO

-- Ładowanie T2
BULK INSERT Aktywacja_Promocji FROM 'C:\Projekty\data\Aktywacja_Promocji_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Gra FROM 'C:\Projekty\data\Gra_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Gracz FROM 'C:\Projekty\data\Gracz_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Kasyno FROM 'C:\Projekty\data\Kasyno_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Pracownik FROM 'C:\Projekty\data\Pracownik_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Promocja FROM 'C:\Projekty\data\Promocja_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Sesja_gry FROM 'C:\Projekty\data\Sesja_gry_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Wizyta FROM 'C:\Projekty\data\Wizyta_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
BULK INSERT Zakup FROM 'C:\Projekty\data\Zakup_T2.csv' WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '\n', CODEPAGE = '65001', TABLOCK);
GO
